# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffb6c760f40b44eba5d5ed465239dc860544a7adfb1ea88a4296404b41146c5cdfe2b0f7a2a9cafc98abb0ee6da074a02714c217750e8dda664d3b925a6cb6a

test:
  secret_key_base: 531c1e0a157b55f3ac1d517e18ed03bd2edb0ec2b4b42426d25aa0e6431eddb958c769cd6c885efe033f893b1705b92d11950f34d170e3cdaea676d2c2ad5505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
